apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory : "64Mi"
        cpu :  "100m"
      limit:
        memory : "128Mi"
        cpu: "150m"