apiVersion: v1
kind: Service
metadata:
  name : nginx-np
spec: 
  type: NodePort
  selector:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
  ports:
  - protocol: TCP
    port: 89
    targetPort: 80
    nodePort: 30001

---
apiVersion: v1
kind: Pod
metadata:
  name : backend-np
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
spec:
  containers:
  - name: nginx
    image: nginx